apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    route:
      receiver: telegram
      repeat_interval: 6h
    receivers:
      - name: telegram
        telegram_configs:
          -             bot_token_file: /etc/alertmanager/secrets/token
            chat_id: 796477198
            parse_mode: HTML