apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: monitoring
  labels:
    app: loki-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-server
  template:
    metadata:
      labels:
        app: loki-server
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.7.3
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki/
            - name: data
              mountPath: /loki
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}
