apiVersion: v1
data:
    COMIC_VINE_API_KEY: ENC[AES256_GCM,data:iXcAgBK/7glaRxjwwLHOYl3keryM3REzRNz9E3ir4V0kkVPMiZO/J72VDocMJIzRlbcgfLDFaBo=,iv:sMb/Ji+FqtF3egs675ekFdR5lkc9K3ZPB433IA9OGrc=,tag:OEtDCqa88nWzilYWBnI29A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:kSCDI7L6KyGmNq68LLzTpYAHGufY7V2uzSqnu6Z/UmtbrrAE8iktAHw8DsGjkthGkESQzdaoqlI4WYUTPP4e2w==,iv:TqZHGkQh9lzYx6HzzoHhuJPSseS4+N7JjEaRoVi3vfM=,tag:WiPxxmvJtPNGayowETFRmw==,type:str]
    HARDCOVER_API_KEY: ENC[AES256_GCM,data:zYDUHZy61e+FmbzNoG/3gXPIQhKvdC+sXG5Bp4Oeg5/xep+K8NBcz/7VPHkq7z8G9saPR0+YNvBYTM05Zt7VJbIkiCI=,iv:Mrej3BETwBlqfhDdq+7AKkhNToRUgAZ7fk9HcVGc9Ls=,tag:SX9R6kIBB/K7NWd2qbuRmw==,type:str]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:gNZlplm08dh6UYAlT0+KeUcG1zH9tcft8SJDZ7GBDjMi3A11fHVoWQ==,iv:7rbU4fZqy62v+6pG+JVvbZHeuRKXhgj3KKdEV5UKP+A=,tag:dZ2xPbQlNLE1oJ+BPVpSrg==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:VrhkT3AvxJi8lcBkJ1bo1Prf4Yw8tN/R7wPOOvoCfNtxrw7zdSEFkQ==,iv:3Iy7oBCyPR5W5ojlXUlmgwNwPz6zSsn7TNVzUfrD5uU=,tag:L+wMc/q+NYbGwkZuPPUzEg==,type:str]
    MAILERSEND_SMTP_PASS: ENC[AES256_GCM,data:IUwDH+YHsCK36DTeqtwwLdlhzVloM8qcTtUNYVfPMi7YM6U2cTarQvsOckDxRe05rsHRhA==,iv:ueGXDsIcTQ7Zof8Nvg7K6FVlm+XML8UiBEmZOfCbE00=,tag:+NM37VpNvTHniEV3qHGIdA==,type:str]
    MAILERSEND_SMTP_USER: ENC[AES256_GCM,data:FFAiW6uhNuNXG7nhgogTiSa41RFyNLLn/Nmc5yFy2qfmOYxnBy9l78RV2JqdOjRkj5k0zM+JdXJQkNYD,iv:vP0HDBU92NAO8c2x97lkNJLFXeRu1pwAqAIVrrUuoQs=,tag:RyKwQk/2dh56jwd61J15nQ==,type:str]
    MAL_CLIENT_ID: ENC[AES256_GCM,data:zEXxxDDPFX2KQ9NjkVcs1LKgUXR+fx/CIQL6Ae5SWSrPl+FTI9dDVKNi7lM=,iv:o4NSYd4WIXI31AC5JcbynubzVRnTalx7/8aoefKE1wQ=,tag:WpDDkI6/M1OnpSKBH3ppmg==,type:str]
    MAL_CLIENT_SECRET: ENC[AES256_GCM,data:6c63M97eZAqKdBMLgleT2vFZYb+g2YWrJJuCtmbfMRWUq4eJErrvs/jn/BVD2RD0oI9ONQ4iXeiEUAXUPGS9uU5NZUL1vceDK33CBrg65Acr56dcZMpMWg==,iv:wKJzx9jkEXvgNEwVcPA8YEPWLoWIRtHEmEWJ5pF1CmQ=,tag:bx6igqmJSr+q77Wu17mynQ==,type:str]
    RAWG_API_KEY: ENC[AES256_GCM,data:Wb8JgV0l4zITbUhS2VeqjzWWw7xuc0fimLY2BWmXZCr0srNKdhC/LDkzyi4=,iv:I2nvflvm5w1qAqb2JcAFrqYuYr6EMcWY9Za+yKwR9yE=,tag:cB8QiMQwOtQc0dPuVnxXEw==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:YoDCPJFwKrTuUFu0jOIvm3d3TR/wybhiVww/2nJJPLpkRv06aQbQlBvpeknFDJvT,iv:udjooHsyrPq0u7HR/9ilXxr8MQ8BWqk+ow9CfaVE93Q=,tag:t6NNWrSCrG4nbldZ9U7OKQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:RcHE8CxsSY3HY6BPM6Q8EDZl3o5crx0stYNeySVBGPxkpBtgeR75s/BwsY2WdyZTtV/7TDt3XZctTS+gHsocb2//9r4O/JYwwmlZhRYMy+28vGfq+DmfUg==,iv:URxLB9kFFaD0sYOXvPIZiI5yOQrt9BwMihOPNS+3fCg=,tag:JCmfJvguWeU9HVuWSeGIag==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:w3zzPkrI8IinolO3AUepIQ3CIC+569Y+gXUzjjOijMd9IXOj2NkNEyYbDh2nyC1U7JzuMd3w2e1Q7lm8BOPh1w==,iv:UdwkkauV+8ZEbkVtpfZ7u6RgaXnOgZAwuhIovF07/ZI=,tag:+0siRQl1Xfr856u8pe83hA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:HGO4/3HOQa1IP/A4Rcz+LgJvEf9U96h6BfTFpIz94dFYQ9NNEyRyrkk2u7o=,iv:ZXcC4ieC2XlpqFrOCY/YVPwsUhlgk5hHQoMrZL98bNc=,tag:dLCtyFCRTv21G/yXT0rOJw==,type:str]
kind: Secret
metadata:
    name: app-secret
    namespace: mediatracker
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbEplRjFwR1p6Z01VOE15
            dHZ2RFhXRGJYVHNuaExMSXVnbDhNdDB1Y0hFCmFlMk1oU2gwNGQwL3pKRFowL3dG
            VG1zRERpVXFrTzZHb1VEOWwySjBaeVEKLS0tIEwyK2lyekFZYzJ4dmQyZFNjdG53
            bEFGdXp3MnIyd0dSNWI3TUlmK1czV3MK0NnnVOoDQ+Bn8G4/0s4k2Ar9oCu3keVd
            sPLRR2nNRKfynil9tDZTRbf3KGfN1pWP6xGBT7XeNatLBJ/F2tMqlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yt509vs6zpwp6h5gpjy62t4rkt2f0gaeg73rlqu690myypa4zfushnzvqj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T10:16:01Z"
    mac: ENC[AES256_GCM,data:WixkuhQqTcTYjTxSIZ63xDfWz/JnBKIU9HebImCx/V5ArVZp6Woe9HuWJmbTJ/n21ur0UI0+CEiMjzvEO1YnmaUJRaezsri18QRx0XEGQz0mq7oVupUPbu95bEDhl7ReqgsiKeE3JqCTSS47Kni7umr5QEGc0fMkee8ZJPjiv54=,iv:sZXNitGBtzhRkayg2pIQxr5XYJJXNkykDQBjOmx+yXo=,tag:Hi+InVYOwsvF/w2tZnMQQQ==,type:str]
    version: 3.13.3
