apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:zHaI+Nm0O+EkHHOs,iv:dw5yLjv4B0DEfoK3kXvcSvb14Sq32ORL6sLzAtKMmR4=,tag:2cV4mYgk8a/X9Wc6bZsOeQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:npf2nn+UaVXNn3Ug,iv:RQ/G4cf0txwbyhnthY8gstsCDbVispyNETzCi0mCDaA=,tag:YawZTgaF74RWqGqp2xfa7A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:+Zqktw==,iv:pqrYld44kUkKSsKKKBpy4STxOQj3rQ9cOHLP74IOmzU=,tag:hEhENuohEL/Q/dqb+xFxpg==,type:str]
kind: Secret
metadata:
    name: db-secret
    namespace: mediatracker
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMGhIRzhiZEw3M1JOKzJL
            eXFxZyt1bjhncTRCSTVkRXl3dng3TG9nTmdRCjRBKzZXNTBtWGlIaC84RDMxSU5X
            ZUc4Z2JTc09FcVNxdzlNQWJ3Tmt0bVEKLS0tIGpaS0lCVGg2dzhaZVI0TjUxQ3k0
            MDlvN241QWtyOTg4NFp2UDRYSVRWbEEKpegYLTWBJo3WuSDd33PINOw0KIj6s3jw
            4dw/9X/tnG+EQaL4rs7HLSCHxKyRsrygwL/slUH5OS2WbepPk/GIYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yt509vs6zpwp6h5gpjy62t4rkt2f0gaeg73rlqu690myypa4zfushnzvqj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T10:16:02Z"
    mac: ENC[AES256_GCM,data:VWumCfDIIobZTTQso1l/iPoBm8H84L2jaWi3uVUdHQpT1WwM0NDy0lTuF2kOzktmSN6wB74pcRKH7WFPgP+pSSmAAOn0dgXRGlIu062pUa/AFh/UdGFwTcSx3QOJAd3qGpVk+CIMhNAFFbjkmvQOoTtEtEWv1KpiaXrNbr8gAR4=,iv:jotJEis/BuRImcIeqrFMdHXS9WGZJ7e/YU+B73DS8Zw=,tag:uQymrUBM1VmxtQzmbawhyQ==,type:str]
    version: 3.13.3
