"""merge heads placeholder (generated earlier but not persisted)"""

from alembic import op
import sqlalchemy as sa

# Alembic revision identifiers
revision = "7e08664b985a"
# The previous head before the manual merge was 20230427m0g0
# (the merge we created earlier). We set it as the sole parent.
# If there were other parallel heads, list them in a tuple.

down_revision = ("20230427m0g0",)
branch_labels = None
depends_on = None


def upgrade() -> None:
    """No schema changes – this file only serves as the Alembic head.
    It replaces the missing autogenerated merge file.
    """
    pass


def downgrade() -> None:
    """Rollback is not required for a placeholder merge revision.
    Raising NotImplementedError makes accidental downgrades obvious.
    """
    raise NotImplementedError("Downgrade of merge placeholder is not supported")
