"""add episodes column

Revision ID: aa7411391eb2
Revises: cdef1234add_email_constraints
Create Date: 2026-04-27 11:58:16.638404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7411391eb2'
down_revision: Union[str, Sequence[str], None] = 'cdef1234add_email_constraints'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_items', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('media_items', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
