"""add provider and description

Revision ID: bdedc21ab4e8
Revises: 
Create Date: 2026-04-22 21:39:43.610880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdedc21ab4e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('media_items', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('media_items', sa.Column('status', sa.String(), nullable=True))
    op.add_column('media_items', sa.Column('score', sa.Integer(), nullable=True))
    op.alter_column('media_items', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uix_provider_external', 'media_items', ['provider', 'external_id'])
    op.add_column('tracking_entries', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_entries', 'created_at')
    op.drop_constraint('uix_provider_external', 'media_items', type_='unique')
    op.alter_column('media_items', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('media_items', 'score')
    op.drop_column('media_items', 'status')
    op.drop_column('media_items', 'description')
    op.drop_column('media_items', 'provider')
    # ### end Alembic commands ###
