import type { MediaItem } from "./media-types";

export const sampleMediaData: MediaItem[] = [
  // Anime
  {
    id: 1,
    title: "Jujutsu Kaisen",
    poster: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    status: "watching",
    currentProgress: 18,
    totalProgress: 24,
    score: 8.9,
    type: "anime",
  },
  {
    id: 2,
    title: "Attack on Titan: The Final Season",
    poster: "https://cdn.myanimelist.net/images/anime/1948/120625.jpg",
    status: "completed",
    currentProgress: 16,
    totalProgress: 16,
    score: 9.1,
    type: "anime",
  },
  {
    id: 3,
    title: "Demon Slayer",
    poster: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
    status: "completed",
    currentProgress: 26,
    totalProgress: 26,
    score: 8.5,
    type: "anime",
  },
  {
    id: 4,
    title: "Spy x Family",
    poster: "https://cdn.myanimelist.net/images/anime/1441/122795.jpg",
    status: "watching",
    currentProgress: 8,
    totalProgress: 12,
    score: 8.7,
    type: "anime",
  },
  {
    id: 5,
    title: "Chainsaw Man",
    poster: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg",
    status: "watching",
    currentProgress: 5,
    totalProgress: 12,
    score: 8.6,
    type: "anime",
  },

  // Movies
  {
    id: 101,
    title: "Inception",
    poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    status: "completed",
    currentProgress: 148,
    totalProgress: 148,
    score: 9.0,
    type: "movies",
  },
  {
    id: 102,
    title: "Interstellar",
    poster: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    status: "completed",
    currentProgress: 169,
    totalProgress: 169,
    score: 9.2,
    type: "movies",
  },
  {
    id: 103,
    title: "Dune: Part Two",
    poster: "https://m.media-amazon.com/images/M/MV5BN2QyZGU4ZDctOWMzMy00NTc5LThlOGQtODhmNDI1NmY5YzAwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    status: "plan-to-watch",
    currentProgress: 0,
    totalProgress: 166,
    type: "movies",
  },

  // TV Shows
  {
    id: 201,
    title: "Breaking Bad",
    poster: "https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_SX300.jpg",
    status: "completed",
    currentProgress: 62,
    totalProgress: 62,
    score: 9.5,
    type: "tv",
  },
  {
    id: 202,
    title: "The Last of Us",
    poster: "https://m.media-amazon.com/images/M/MV5BZGUzYTI3M2EtZmM0Yy00NGUyLWI4ODEtN2Q3ZGJlYzhhZjU3XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    status: "watching",
    currentProgress: 5,
    totalProgress: 9,
    score: 8.8,
    type: "tv",
  },
  {
    id: 203,
    title: "Severance",
    poster: "https://m.media-amazon.com/images/M/MV5BMjkwZjcwMGQtNDAzOC00YjJiLThiYTgtNWU3ZjRiZmY2YzEzXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_SX300.jpg",
    status: "watching",
    currentProgress: 3,
    totalProgress: 9,
    score: 8.7,
    type: "tv",
  },

  // Books
  {
    id: 301,
    title: "Project Hail Mary",
    poster: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1597695864i/54493401.jpg",
    status: "completed",
    currentProgress: 496,
    totalProgress: 496,
    score: 9.0,
    type: "books",
  },
  {
    id: 302,
    title: "Atomic Habits",
    poster: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655988385i/40121378.jpg",
    status: "watching",
    currentProgress: 120,
    totalProgress: 320,
    score: 8.5,
    type: "books",
  },

  // Manga
  {
    id: 401,
    title: "One Piece",
    poster: "https://cdn.myanimelist.net/images/manga/2/253146.jpg",
    status: "watching",
    currentProgress: 1089,
    totalProgress: 1120,
    score: 9.2,
    type: "manga",
  },
  {
    id: 402,
    title: "Berserk",
    poster: "https://cdn.myanimelist.net/images/manga/1/157897.jpg",
    status: "watching",
    currentProgress: 280,
    totalProgress: 374,
    score: 9.5,
    type: "manga",
  },
  {
    id: 403,
    title: "Vagabond",
    poster: "https://cdn.myanimelist.net/images/manga/1/259070.jpg",
    status: "on-hold",
    currentProgress: 150,
    totalProgress: 327,
    score: 9.0,
    type: "manga",
  },

  // Manhwa
  {
    id: 501,
    title: "Solo Leveling",
    poster: "https://cdn.myanimelist.net/images/manga/3/222295.jpg",
    status: "completed",
    currentProgress: 179,
    totalProgress: 179,
    score: 8.8,
    type: "manhwa",
  },
  {
    id: 502,
    title: "Tower of God",
    poster: "https://cdn.myanimelist.net/images/manga/1/260791.jpg",
    status: "watching",
    currentProgress: 450,
    totalProgress: 600,
    score: 8.5,
    type: "manhwa",
  },

  // Manhua
  {
    id: 601,
    title: "The Beginning After The End",
    poster: "https://cdn.myanimelist.net/images/manga/1/232632.jpg",
    status: "watching",
    currentProgress: 120,
    totalProgress: 200,
    score: 8.3,
    type: "manhua",
  },

  // Games
  {
    id: 701,
    title: "Elden Ring",
    poster: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg",
    status: "completed",
    currentProgress: 120,
    totalProgress: 120,
    score: 9.5,
    type: "games",
  },
  {
    id: 702,
    title: "Baldur's Gate 3",
    poster: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/capsule_616x353.jpg",
    status: "watching",
    currentProgress: 85,
    totalProgress: 150,
    score: 9.3,
    type: "games",
  },
  {
    id: 703,
    title: "Hades II",
    poster: "https://cdn.cloudflare.steamstatic.com/steam/apps/1145350/capsule_616x353.jpg",
    status: "plan-to-watch",
    currentProgress: 0,
    totalProgress: 50,
    type: "games",
  },

  // Dramas
  {
    id: 801,
    title: "Squid Game",
    poster: "https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg",
    status: "completed",
    currentProgress: 9,
    totalProgress: 9,
    score: 8.0,
    type: "dramas",
  },
  {
    id: 802,
    title: "Reply 1988",
    poster: "https://m.media-amazon.com/images/M/MV5BODYzMzRiMmEtOWRhYS00YjI0LWI0NjYtZjY4NTU2YjE2NDVjXkEyXkFqcGdeQXVyNDkzNTM2ODg@._V1_SX300.jpg",
    status: "watching",
    currentProgress: 10,
    totalProgress: 20,
    score: 9.2,
    type: "dramas",
  },

  // Cartoons
  {
    id: 901,
    title: "Arcane",
    poster: "https://m.media-amazon.com/images/M/MV5BYmU5OWM5ZTAtNjUzOC00NmUyLTgyOWMtMjlkNjdlMDAzMzU1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    status: "completed",
    currentProgress: 9,
    totalProgress: 9,
    score: 9.4,
    type: "cartoons",
  },
  {
    id: 902,
    title: "Invincible",
    poster: "https://m.media-amazon.com/images/M/MV5BNWYwMzRmZDctNDJiNy00NDNjLWJmNGYtNDE0YzZkYmIyODVkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    status: "watching",
    currentProgress: 12,
    totalProgress: 16,
    score: 8.9,
    type: "cartoons",
  },
  {
    id: 903,
    title: "Avatar: The Last Airbender",
    poster: "https://m.media-amazon.com/images/M/MV5BODc5YTBhMTItMjhkNi00ZTIxLWI0YjAtNTZmOTY0YjRlZGQ0XkEyXkFqcGdeQXVyODUwNjEzMzg@._V1_SX300.jpg",
    status: "completed",
    currentProgress: 61,
    totalProgress: 61,
    score: 9.3,
    type: "cartoons",
  },

  // Animated Movies
  {
    id: 1001,
    title: "Spider-Man: Across the Spider-Verse",
    poster: "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg",
    status: "completed",
    currentProgress: 140,
    totalProgress: 140,
    score: 9.1,
    type: "animated-movies",
  },
  {
    id: 1002,
    title: "Spirited Away",
    poster: "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    status: "completed",
    currentProgress: 125,
    totalProgress: 125,
    score: 9.3,
    type: "animated-movies",
  },
  {
    id: 1003,
    title: "Your Name",
    poster: "https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_SX300.jpg",
    status: "completed",
    currentProgress: 106,
    totalProgress: 106,
    score: 9.0,
    type: "animated-movies",
  },

  // Novels
  {
    id: 1101,
    title: "Sword Art Online",
    poster: "https://cdn.myanimelist.net/images/manga/1/54633.jpg",
    status: "on-hold",
    currentProgress: 5,
    totalProgress: 27,
    score: 7.5,
    type: "novels",
  },
  {
    id: 1102,
    title: "Mushoku Tensei",
    poster: "https://cdn.myanimelist.net/images/manga/3/215609.jpg",
    status: "watching",
    currentProgress: 12,
    totalProgress: 26,
    score: 8.5,
    type: "novels",
  },
  {
    id: 1103,
    title: "Re:Zero",
    poster: "https://cdn.myanimelist.net/images/manga/1/170906.jpg",
    status: "plan-to-watch",
    currentProgress: 0,
    totalProgress: 35,
    type: "novels",
  },
];
